import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { SiteShell } from '@/components/site-shell';
import { getProject } from '@/lib/api';
type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const project = await getProject((await params).slug); if (!project) return {}; const image = project.media.find((item) => item.type === 'cover' || item.type === 'thumbnail')?.media.publicUrl; return { title: project.seoTitle ?? project.title, description: project.seoDescription ?? project.shortSummary, openGraph: { title: project.seoTitle ?? project.title, description: project.seoDescription ?? project.shortSummary ?? undefined, images: image ? [image] : [] } }; }
export default async function ProjectPage({ params }: Props) {
  const project = await getProject((await params).slug); if (!project) notFound();
  const cover = project.media.find((item) => item.type === 'cover')?.media;
  return <SiteShell><main className="mx-auto max-w-[1600px] px-6 py-20 md:px-12"><div className="font-mono text-[10px] uppercase tracking-[.3em] text-accent">Case study / {project.year}</div><h1 className="my-10 max-w-6xl text-7xl font-bold uppercase leading-[.85] tracking-[-.06em] md:text-9xl">{project.title}</h1><p className="max-w-3xl text-xl opacity-70 md:text-3xl">{project.subtitle ?? project.shortSummary}</p>{cover?.publicUrl && <img src={cover.publicUrl} alt={cover.altText ?? project.title} className="mt-16 aspect-[16/8] w-full object-cover" />}<div className="mt-20 grid border-t border-[var(--border-color)] md:grid-cols-3">{[['Problema', project.problem], ['Solución', project.solution], ['Resultado', project.result]].map(([label, value]) => <section key={label} className="border-b border-r border-[var(--border-color)] py-10 pr-8"><h2 className="font-mono text-[10px] uppercase tracking-widest text-accent">{label}</h2><p className="mt-6 leading-relaxed opacity-75">{value || 'Información en preparación.'}</p></section>)}</div><div className="mt-20 grid gap-12">{project.sections?.map((section) => <CaseSection key={section.id} section={section} />)}</div><div className="mt-20 grid gap-4 md:grid-cols-2">{project.media.filter((item) => item.type === 'gallery').map((item) => item.media.publicUrl && <figure key={item.id}><img src={item.media.publicUrl} alt={item.media.altText ?? item.title ?? project.title} className="aspect-[4/3] w-full object-cover" />{item.caption && <figcaption className="mt-2 text-sm opacity-50">{item.caption}</figcaption>}</figure>)}</div><div className="mt-16 flex flex-wrap gap-3">{project.links.map((link) => <a key={link.id} href={link.url} target="_blank" rel="noreferrer" className="border border-[var(--border-color)] px-5 py-3 font-mono text-[10px] uppercase tracking-widest">{link.label} ↗</a>)}</div></main></SiteShell>;
}
function CaseSection({ section }: { section: { id: string; type: string; title: string | null; content: unknown } }) { const content = section.content as Record<string, unknown>; const text = typeof content === 'string' ? content : String(content?.text ?? content?.quote ?? ''); const metrics = Array.isArray(content?.items) ? content.items as { label?: string; value?: string }[] : []; return <section className="border-t border-[var(--border-color)] pt-8"><p className="font-mono text-[10px] uppercase tracking-[.3em] text-accent">{section.type}</p>{section.title && <h2 className="mt-5 text-4xl font-bold uppercase tracking-tight md:text-6xl">{section.title}</h2>}{metrics.length ? <div className="mt-8 grid gap-px bg-[var(--border-color)] md:grid-cols-3">{metrics.map((metric, index) => <div key={index} className="bg-[var(--bg-primary)] p-8"><strong className="text-4xl">{metric.value}</strong><p className="mt-3 text-sm opacity-60">{metric.label}</p></div>)}</div> : <p className="mt-7 max-w-4xl whitespace-pre-line text-lg leading-relaxed opacity-70">{text}</p>}</section>; }
