import Link from 'next/link';
import { SiteFooter, SiteHeader } from './components/SiteHeader';
import { ProjectCard } from './components/ProjectCard';
import { getProjects } from './lib/api';

export default async function Home() {
  const projects = (await getProjects()).slice(0, 4);
  return <><SiteHeader /><main><section className="hero"><div className="eyebrow">FULL-STACK DEVELOPER · SYSTEMS BUILDER</div><h1>Intelligent web<br /><em>platforms.</em></h1><p className="hero-lede">I design and build digital systems that combine modern interfaces, automation, AI and reliable infrastructure to solve real business problems.</p><div className="hero-actions"><Link href="/projects" className="button button-primary">View projects <span>↗</span></Link><Link href="/contact" className="button button-ghost">Start a conversation</Link></div><div className="hero-meta"><span>Based in Mexico</span><span>Available for selected projects</span><span>↑ Scroll to explore</span></div></section><section className="section section-dark"><div className="section-heading"><div><span className="eyebrow">SELECTED WORK</span><h2>Systems with a<br /><em>point of view.</em></h2></div><Link href="/projects" className="text-link">View all projects ↗</Link></div><div className="project-grid">{projects.length ? projects.map((project) => <ProjectCard key={project.id} project={project} />) : <div className="empty-state">Projects are being connected to the CMS.</div>}</div></section><section className="section capabilities"><span className="eyebrow">WHAT I BUILD</span><div className="capability-grid"><article><span>01</span><h3>Product interfaces</h3><p>Premium, responsive frontends that turn complex workflows into clear experiences.</p></article><article><span>02</span><h3>Business platforms</h3><p>Dashboards, CMS products and internal tools designed around how teams actually work.</p></article><article><span>03</span><h3>Automation & AI</h3><p>Connected systems that remove repetitive work and create leverage for growing teams.</p></article></div></section><section className="section cta"><span className="eyebrow">HAVE A COMPLEX PROBLEM?</span><h2>Let’s make it<br /><em>legible.</em></h2><Link href="/contact" className="button button-primary">Tell me about it ↗</Link></section></main><SiteFooter /></>;
}
