import Link from 'next/link';
import { SiteShell } from '@/components/site-shell';
import { ProjectGrid } from '@/components/project-grid';
import { getProjects } from '@/lib/api';
import { LangText } from '@/components/lang-text';
const solutions = [['01', 'Intelligent platforms', 'Aplicaciones y portales que conectan frontend, datos, usuarios y operaciones.'], ['02', 'Custom CMS', 'Sistemas editoriales propios para administrar contenido sin depender del código.'], ['03', 'AI & Automation', 'Flujos con IA, scraping, APIs y automatización para reducir trabajo manual.'], ['04', 'Digital products', 'Experiencias rápidas y escalables diseñadas alrededor de objetivos de negocio.']];
export const dynamic = 'force-dynamic';
export default async function HomePage() { const projects = await getProjects(); const featured = projects.filter((project) => project.featured).slice(0, 4); return <SiteShell><main>
  <section className="flex min-h-[78vh] flex-col justify-between py-16 md:py-24"><p className="eyebrow">Full-stack developer · Product builder</p><div><h1 className="display-title max-w-[1400px]"><LangText en="Intelligent web platforms." es="Plataformas web inteligentes." /></h1><div className="mt-10 grid gap-8 border-t border-[var(--border-color)] pt-8 md:grid-cols-2"><p className="max-w-2xl text-xl leading-relaxed muted md:text-2xl"><LangText en="I design and build digital systems combining frontend, CMS, automation, AI and technical architecture." es="Diseño y desarrollo sistemas digitales que combinan frontend, CMS, automatización, IA y arquitectura técnica." /></p><div className="flex items-start gap-3 md:justify-end"><Link href="/case-studies" style={{ backgroundColor: 'var(--text-primary)', color: 'var(--bg-primary)' }} className="px-6 py-4 font-mono text-[10px] uppercase tracking-widest"><LangText en="Explore case studies" es="Explorar casos" /></Link><Link href="/contact" className="border border-[var(--border-color)] px-6 py-4 font-mono text-[10px] uppercase tracking-widest"><LangText en="Contact" es="Contacto" /></Link></div></div></div></section>
  <section className="border-y border-[var(--border-color)] py-20"><div className="mb-12 flex items-end justify-between"><div><p className="eyebrow">Selected work</p><h2 className="section-title mt-5"><LangText en="Featured projects" es="Proyectos destacados" /></h2></div><Link href="/projects" className="hidden font-mono text-[10px] uppercase tracking-widest md:block"><LangText en="View all ↗" es="Ver todos ↗" /></Link></div><ProjectGrid projects={featured.length ? featured : projects.slice(0, 4)} /></section>
  <section className="mx-auto max-w-[1600px] px-6 py-24 md:px-12"><p className="eyebrow">What I build</p><h2 className="section-title my-10 max-w-5xl">Systems, not just screens.</h2><div className="grid border-l border-t border-[var(--border-color)] md:grid-cols-2">{solutions.map(([number, title, text]) => <article key={number} className="min-h-72 border-b border-r border-[var(--border-color)] p-8 md:p-10"><span className="font-mono text-[10px] text-[var(--accent)]">{number}</span><h3 className="mt-16 text-3xl font-semibold uppercase">{title}</h3><p className="mt-5 max-w-lg muted">{text}</p></article>)}</div></section>
  <section className="border-t border-[var(--border-color)] bg-[var(--bg-secondary)]"><div className="mx-auto max-w-[1600px] px-6 py-24 md:px-12"><p className="eyebrow">Selected technologies</p><div className="mt-10 flex flex-wrap gap-x-10 gap-y-5 text-2xl font-semibold md:text-4xl">{['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'WordPress', 'Supabase', 'n8n', 'OpenAI'].map((tech) => <span key={tech}>{tech}</span>)}</div></div></section>
  <section className="mx-auto max-w-[1600px] px-6 py-28 md:px-12"><p className="eyebrow">Have a complex idea?</p><h2 className="section-title my-10 max-w-6xl">Let’s turn it into a useful product.</h2><Link href="/contact" className="inline-block border-b border-current pb-2 text-xl">Start a conversation ↗</Link></section>
</main></SiteShell>; }
