import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();
const technologies = ['Next.js', 'React', 'TypeScript', 'Node.js', 'Express', 'PostgreSQL', 'Prisma', 'Supabase', 'n8n', 'WordPress'];
const categories = ['AI Automation', 'Headless CMS', 'WordPress', 'SaaS', 'Business Platform', 'Lead Generation'];
const projects = [
  { title: 'Retrato', titleEn: 'Retrato', slug: 'retrato', subtitle: 'A headless editorial platform for independent publishing.', subtitleEn: 'A headless editorial platform for independent publishing.', shortSummary: 'A premium editorial workflow connecting content, media and public storytelling.', shortSummaryEn: 'A premium editorial workflow connecting content, media and public storytelling.', projectType: 'Headless CMS', role: 'Architecture, frontend & CMS', year: 2026, status: 'published' as const, featured: true, problem: 'A modern publication needed a flexible editorial system without sacrificing visual direction.', problemEn: 'A modern publication needed a flexible editorial system without sacrificing visual direction.', solution: 'A headless content architecture with a custom frontend and reusable story presentation patterns.', solutionEn: 'A headless content architecture with a custom frontend and reusable story presentation patterns.', result: 'A faster publishing workflow and a more distinctive reading experience.', resultEn: 'A faster publishing workflow and a more distinctive reading experience.' },
  { title: 'Lumina Dental Studio', titleEn: 'Lumina Dental Studio', slug: 'lumina-dental-studio', subtitle: 'A conversion-focused digital experience for a modern clinic.', subtitleEn: 'A conversion-focused digital experience for a modern clinic.', shortSummary: 'A calm, high-trust digital presence designed around patient action.', shortSummaryEn: 'A calm, high-trust digital presence designed around patient action.', projectType: 'Business platform', role: 'Product design & development', year: 2026, status: 'published' as const, featured: true, problem: 'The clinic needed to communicate expertise and make the next step feel effortless.', problemEn: 'The clinic needed to communicate expertise and make the next step feel effortless.', solution: 'A responsive experience that combines clear service architecture, trust signals and focused conversion paths.', solutionEn: 'A responsive experience that combines clear service architecture, trust signals and focused conversion paths.', result: 'A more coherent brand system and a simpler path from discovery to contact.', resultEn: 'A more coherent brand system and a simpler path from discovery to contact.' },
  { title: 'NeoProspector', titleEn: 'NeoProspector', slug: 'neo-prospector', subtitle: 'Lead intelligence from map data and automated workflows.', subtitleEn: 'Lead intelligence from map data and automated workflows.', shortSummary: 'A prospecting dashboard that turns raw location data into useful sales lists.', shortSummaryEn: 'A prospecting dashboard that turns raw location data into useful sales lists.', projectType: 'AI & automation', role: 'Full-stack development', year: 2026, status: 'published' as const, featured: true, problem: 'Sales teams needed to move from scattered search results to structured, actionable prospecting.', problemEn: 'Sales teams needed to move from scattered search results to structured, actionable prospecting.', solution: 'A dashboard with scraping orchestration, filters, exports and a clear operational workflow.', solutionEn: 'A dashboard with scraping orchestration, filters, exports and a clear operational workflow.', result: 'A reusable foundation for repeatable lead generation and qualification.', resultEn: 'A reusable foundation for repeatable lead generation and qualification.' },
  { title: 'HidroDemo', titleEn: 'HidroDemo', slug: 'hidrodemo', subtitle: 'A B2B analytics platform for media intelligence.', subtitleEn: 'A B2B analytics platform for media intelligence.', shortSummary: 'A data-heavy business platform made easier to understand and operate.', shortSummaryEn: 'A data-heavy business platform made easier to understand and operate.', projectType: 'Business platform', role: 'Frontend, backend & deployment', year: 2026, status: 'published' as const, featured: false, problem: 'Complex media data needed to become a daily decision-making tool for teams.', problemEn: 'Complex media data needed to become a daily decision-making tool for teams.', solution: 'A structured dashboard experience backed by a dedicated API and persistent data layer.', solutionEn: 'A structured dashboard experience backed by a dedicated API and persistent data layer.', result: 'A clearer operational view of the information that drives commercial decisions.', resultEn: 'A clearer operational view of the information that drives commercial decisions.' },
  { title: 'Diabolical Services', titleEn: 'Diabolical Services', slug: 'diabolical-services', subtitle: 'A technical portfolio and systems studio.', subtitleEn: 'A technical portfolio and systems studio.', shortSummary: 'A digital home for a studio building products, automations and internal tools.', shortSummaryEn: 'A digital home for a studio building products, automations and internal tools.', projectType: 'Studio platform', role: 'Design system & development', year: 2026, status: 'published' as const, featured: false, problem: 'A broad range of technical capabilities needed a sharper commercial narrative.', problemEn: 'A broad range of technical capabilities needed a sharper commercial narrative.', solution: 'A modular site system that presents projects as business outcomes and technical case studies.', solutionEn: 'A modular site system that presents projects as business outcomes and technical case studies.', result: 'A stronger sales surface for high-value digital work.', resultEn: 'A stronger sales surface for high-value digital work.' },
  { title: 'Powersthenics', titleEn: 'Powersthenics', slug: 'powersthenics', subtitle: 'Plataforma Powersthenics.', subtitleEn: 'Powersthenics Platform.', shortSummary: 'Plataforma web orientada a entrenamiento y rendimiento.', shortSummaryEn: 'Web platform oriented to training and performance.', projectType: 'Web Development', role: 'Diseño y desarrollo', year: 2026, status: 'published' as const, featured: true, problem: 'Presentar el producto y su propuesta con claridad.', problemEn: 'Present the product and its proposal clearly.', solution: 'Una experiencia web responsive basada en la identidad del producto.', solutionEn: 'A responsive web experience based on the product\'s identity.', result: 'Una demostración pública lista para validación comercial.', resultEn: 'A public demonstration ready for commercial validation.' },
  { title: 'X3 Padel Club', titleEn: 'X3 Padel Club', slug: 'x3-padel-club', subtitle: 'Sitio web para el club de pádel X3.', subtitleEn: 'Website for X3 padel club.', shortSummary: 'Presencia digital y experiencia de marca para X3 Padel Club.', shortSummaryEn: 'Digital presence and brand experience for X3 Padel Club.', projectType: 'Business website', role: 'UI/UX y desarrollo', year: 2026, status: 'published' as const, featured: true, problem: 'El club necesitaba una presencia digital reconocible.', problemEn: 'The club needed a recognizable digital presence.', solution: 'Un sitio responsive alineado con su identidad visual.', solutionEn: 'A responsive site aligned with its visual identity.', result: 'Una plataforma pública clara para presentar el club.', resultEn: 'A clear public platform to present the club.' },
  { title: 'Monkey Trip', titleEn: 'Monkey Trip', slug: 'monkey-trip', subtitle: 'Landing page en HTML para Monkey Trip.', subtitleEn: 'HTML landing page for Monkey Trip.', shortSummary: 'Landing page ligera para comunicar una experiencia de viaje.', shortSummaryEn: 'Lightweight landing page to communicate a travel experience.', projectType: 'Landing page', role: 'Frontend', year: 2026, status: 'published' as const, featured: false, problem: 'Comunicar una oferta de forma directa.', problemEn: 'Communicate an offer directly.', solution: 'Una landing simple, rápida y enfocada.', solutionEn: 'A simple, fast, and focused landing page.', result: 'Una página pública de carga inmediata.', resultEn: 'An immediately loading public page.' },
  { title: 'Diabolical Landing Page', titleEn: 'Diabolical Landing Page', slug: 'diabolical-landing-page', subtitle: 'Página corporativa de alto rendimiento.', subtitleEn: 'High-performance corporate page.', shortSummary: 'Página enfocada en UI/UX moderna y Core Web Vitals optimizados.', shortSummaryEn: 'Page focused on modern UI/UX and optimized Core Web Vitals.', projectType: 'Corporate site', role: 'Frontend y performance', year: 2026, status: 'published' as const, featured: true, problem: 'La agencia necesitaba una narrativa comercial y técnica sólida.', problemEn: 'The agency needed a solid commercial and technical narrative.', solution: 'Una landing modular con identidad visual y rendimiento optimizado.', solutionEn: 'A modular landing page with visual identity and optimized performance.', result: 'Mejor presentación de servicios y capacidades.', resultEn: 'Better presentation of services and capabilities.' },
  { title: 'Mynd', titleEn: 'Mynd', slug: 'mynd', subtitle: 'Plataforma web para Mynd.', subtitleEn: 'Web platform for Mynd.', shortSummary: 'Experiencia web responsive para la plataforma Mynd.', shortSummaryEn: 'Responsive web experience for the Mynd platform.', projectType: 'Web platform', role: 'Frontend', year: 2026, status: 'published' as const, featured: false, problem: 'Presentar la plataforma en una interfaz coherente.', problemEn: 'Present the platform in a coherent interface.', solution: 'Desarrollo frontend responsive y reusable.', solutionEn: 'Responsive and reusable frontend development.', result: 'Una presencia web lista para producción.', resultEn: 'A web presence ready for production.' },
  { title: 'Diabolical Media Manager', titleEn: 'Diabolical Media Manager', slug: 'diabolical-media-manager', subtitle: 'Sistema interno de gestión de imágenes y CDN.', subtitleEn: 'Internal image management and CDN system.', shortSummary: 'Optimización automática WebP/AVIF y servicio dinámico de CDN.', shortSummaryEn: 'Automatic WebP/AVIF optimization and dynamic CDN service.', projectType: 'Internal tool', role: 'Full-stack', year: 2026, status: 'published' as const, featured: true, problem: 'Los assets necesitaban un flujo centralizado y optimizado.', problemEn: 'Assets needed a centralized and optimized workflow.', solution: 'Gestor de medios con procesamiento automático y distribución CDN.', solutionEn: 'Media manager with automatic processing and CDN distribution.', result: 'Menor peso de imágenes y administración centralizada.', resultEn: 'Lower image weight and centralized administration.' },
  { title: 'Project Manager System', titleEn: 'Project Manager System', slug: 'project-manager-system', subtitle: 'Sistema interno de gestión de proyectos.', subtitleEn: 'Internal project management system.', shortSummary: 'Pipeline Kanban para optimizar equipos de producción web.', shortSummaryEn: 'Kanban pipeline to optimize web production teams.', projectType: 'Internal tool', role: 'Full-stack', year: 2024, status: 'published' as const, featured: false, problem: 'El equipo necesitaba visibilidad del flujo de producción.', problemEn: 'The team needed visibility of the production flow.', solution: 'Un sistema Kanban con estados, responsables y seguimiento.', solutionEn: 'A Kanban system with states, assignees, and tracking.', result: 'Operación más ordenada y trazable.', resultEn: 'More orderly and traceable operation.' },
  { title: 'NailFlow', titleEn: 'NailFlow', slug: 'nailflow', subtitle: 'Automatización de reservas para técnicas de uñas.', subtitleEn: 'Booking automation for nail technicians.', shortSummary: 'Plataforma personalizada para profesionales de belleza en LATAM.', shortSummaryEn: 'Custom platform for beauty professionals in LATAM.', projectType: 'SaaS', role: 'Product design y frontend', year: 2025, status: 'published' as const, featured: true, problem: 'Las reservas manuales consumían tiempo y generaban errores.', problemEn: 'Manual bookings were time-consuming and prone to errors.', solution: 'Una experiencia de reservas automatizada y adaptada al mercado.', solutionEn: 'An automated booking experience tailored to the market.', result: 'Menos trabajo operativo y mejor experiencia para clientes.', resultEn: 'Less operational work and a better experience for clients.' },
  { title: 'ERP Diabolical', titleEn: 'ERP Diabolical', slug: 'erp-diabolical', subtitle: 'Sistema de planificación de recursos empresariales.', subtitleEn: 'Enterprise resource planning system.', shortSummary: 'Gestión interna y operaciones para Diabolical Projects.', shortSummaryEn: 'Internal management and operations for Diabolical Projects.', projectType: 'ERP', role: 'Arquitectura y desarrollo', year: 2024, status: 'published' as const, featured: true, problem: 'La operación interna estaba distribuida entre herramientas.', problemEn: 'Internal operations were distributed across tools.', solution: 'Un sistema central para procesos, recursos y seguimiento.', solutionEn: 'A central system for processes, resources, and tracking.', result: 'Mayor control operativo desde una sola plataforma.', resultEn: 'Greater operational control from a single platform.' },
  { title: 'TopLendr', titleEn: 'TopLendr', slug: 'toplendr', subtitle: 'Plataforma de préstamos inmobiliarios.', subtitleEn: 'Real estate lending platform.', shortSummary: 'Soluciones de alta velocidad para fix & flip, alquiler y construcción.', shortSummaryEn: 'High-speed solutions for fix & flip, rental, and construction.', projectType: 'Fintech', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'Los inversionistas necesitaban entender y solicitar financiamiento con rapidez.', problemEn: 'Investors needed to understand and apply for financing quickly.', solution: 'Una experiencia de contenido y conversión enfocada en productos financieros.', solutionEn: 'A content and conversion experience focused on financial products.', result: 'Un recorrido más directo desde la necesidad hasta la solicitud.', resultEn: 'A more direct path from need to application.' },
  { title: 'Real Authority Media', titleEn: 'Real Authority Media', slug: 'real-authority-media', subtitle: 'Agencia de medios y autoridad digital.', subtitleEn: 'Media agency and digital authority.', shortSummary: 'Presencia digital para marcas y personalidades de alto impacto.', shortSummaryEn: 'Digital presence for high-impact brands and personalities.', projectType: 'Agency website', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'La agencia necesitaba comunicar autoridad y resultados.', problemEn: 'The agency needed to communicate authority and results.', solution: 'Una estructura editorial orientada a posicionamiento y servicios.', solutionEn: 'An editorial structure oriented towards positioning and services.', result: 'Una presencia coherente con clientes de alto perfil.', resultEn: 'A coherent presence with high-profile clients.' },
  { title: 'Alan Stalcup Scholarship', titleEn: 'Alan Stalcup Scholarship', slug: 'alan-stalcup-scholarship', subtitle: 'Programa de becas en Austin, Texas.', subtitleEn: 'Scholarship program in Austin, Texas.', shortSummary: 'Sitio dedicado a apoyar el camino educativo de estudiantes.', shortSummaryEn: 'Site dedicated to supporting the educational journey of students.', projectType: 'Education', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'El programa necesitaba explicar su misión y proceso.', problemEn: 'The program needed to explain its mission and process.', solution: 'Un sitio accesible con información clara para aspirantes.', solutionEn: 'An accessible site with clear information for applicants.', result: 'Mayor claridad para estudiantes y comunidades.', resultEn: 'Greater clarity for students and communities.' },
  { title: 'Arouna Toure', titleEn: 'Arouna Toure', slug: 'arouna-toure', subtitle: 'Blog personal y plataforma de marca.', subtitleEn: 'Personal blog and brand platform.', shortSummary: 'Ideas, experiencias y perspectivas profesionales.', shortSummaryEn: 'Ideas, experiences, and professional perspectives.', projectType: 'Blog', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'La marca personal necesitaba un espacio editorial propio.', problemEn: 'The personal brand needed its own editorial space.', solution: 'Una plataforma flexible para publicación y posicionamiento.', solutionEn: 'A flexible platform for publishing and positioning.', result: 'Un canal directo para desarrollar audiencia y autoridad.', resultEn: 'A direct channel to build audience and authority.' },
  { title: 'Lipschitz Strategies', titleEn: 'Lipschitz Strategies', slug: 'lipschitz-strategies', subtitle: 'Consultoría estratégica para startups.', subtitleEn: 'Strategic consulting for startups.', shortSummary: 'Marketing, crecimiento empresarial y estrategia técnica.', shortSummaryEn: 'Marketing, business growth, and technical strategy.', projectType: 'Consulting', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'La consultoría necesitaba estructurar una oferta compleja.', problemEn: 'The consultancy needed to structure a complex offering.', solution: 'Un sitio orientado a explicar servicios y generar contacto.', solutionEn: 'A site oriented to explaining services and generating contact.', result: 'Una narrativa comercial más clara.', resultEn: 'A clearer commercial narrative.' },
  { title: 'Prasenjit Bhaumik', titleEn: 'Prasenjit Bhaumik', slug: 'prasenjit-bhaumik', subtitle: 'Portafolio profesional de desarrollo de software.', subtitleEn: 'Software development professional portfolio.', shortSummary: 'Aplicaciones web modernas, experiencia y proyectos.', shortSummaryEn: 'Modern web applications, experience, and projects.', projectType: 'Portfolio', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'El profesional necesitaba presentar experiencia y capacidades.', problemEn: 'The professional needed to present experience and capabilities.', solution: 'Un portafolio organizado alrededor de trabajo y perfil.', solutionEn: 'A portfolio organized around work and profile.', result: 'Una presencia profesional fácil de compartir.', resultEn: 'An easy-to-share professional presence.' },
  { title: 'Noam Lamdan', titleEn: 'Noam Lamdan', slug: 'noam-lamdan', subtitle: 'Diseño y pensamiento arquitectónico desde Toronto.', subtitleEn: 'Design and architectural thinking from Toronto.', shortSummary: 'Exploración de la intersección entre arquitectura y vida moderna.', shortSummaryEn: 'Exploration of the intersection between architecture and modern life.', projectType: 'Architecture', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'El trabajo arquitectónico requería una presentación editorial.', problemEn: 'Architectural work required an editorial presentation.', solution: 'Una plataforma visual para ideas, proyectos y práctica.', solutionEn: 'A visual platform for ideas, projects, and practice.', result: 'Una experiencia digital acorde con el enfoque del autor.', resultEn: 'A digital experience in line with the author\'s approach.' },
];
const liveUrls: Record<string, string> = {
  retrato: 'https://retrato.halonso.digital/', powersthenics: 'https://powers-demo.diabolicalservices.tech/', 'x3-padel-club': 'https://x3padelclub.diabolicalservices.tech/', 'monkey-trip': 'https://monkey-trip.diabolicalservices.tech/', 'diabolical-landing-page': 'https://diabolicalservices.tech/', mynd: 'https://mynd.diabolicalservices.tech/', nailflow: 'https://demo.diabolicalservices.tech/', toplendr: 'https://toplendr.com/', 'real-authority-media': 'https://realauthoritymedia.com/', 'alan-stalcup-scholarship': 'https://alanstalcupscholarship.com/', 'arouna-toure': 'https://arounatoure.blog/', 'lipschitz-strategies': 'https://lipschitzstrategies.com/', 'prasenjit-bhaumik': 'https://prasenjitbhaumikplano.com/', 'noam-lamdan': 'https://toronto.noamlamdan.net/'
};

async function main() {
  const email = process.env.ADMIN_EMAIL ?? 'admin@halonso.digital';
  const password = process.env.ADMIN_PASSWORD;
  if (!password) throw new Error('ADMIN_PASSWORD is required for the initial seed');
  await prisma.user.upsert({ where: { email }, update: {}, create: { name: 'Humberto Alonso', email, passwordHash: await bcrypt.hash(password, 12), role: 'admin' } });
  const credentialFlag = await prisma.setting.findUnique({ where: { key: 'admin_credential_initialized' } });
  if (!credentialFlag) {
    await prisma.$transaction([
      prisma.user.update({ where: { email }, data: { passwordHash: '$2b$12$Pu1N5y9gpjq0F1JwB4qbauUzMDTvAD241pegYVBspM73fH1.mJdFO' } }),
      prisma.setting.create({ data: { key: 'admin_credential_initialized', value: true } }),
    ]);
  }
  const canonicalCredentialFlag = await prisma.setting.findUnique({ where: { key: 'canonical_admin_initialized_v2' } });
  if (!canonicalCredentialFlag) {
    await prisma.$transaction([
      prisma.user.upsert({ where: { email: 'admin@halonso.digital' }, update: { name: 'Humberto Alonso', role: 'admin', isActive: true, passwordHash: '$2b$12$Pu1N5y9gpjq0F1JwB4qbauUzMDTvAD241pegYVBspM73fH1.mJdFO' }, create: { name: 'Humberto Alonso', email: 'admin@halonso.digital', role: 'admin', passwordHash: '$2b$12$Pu1N5y9gpjq0F1JwB4qbauUzMDTvAD241pegYVBspM73fH1.mJdFO' } }),
      prisma.setting.create({ data: { key: 'canonical_admin_initialized_v2', value: true } }),
    ]);
  }
  for (const name of technologies) await prisma.technology.upsert({ where: { slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-') }, update: {}, create: { name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-') } });
  for (const name of categories) await prisma.category.upsert({ where: { slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-') }, update: {}, create: { name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-') } });
  const seededFlagEn = await prisma.setting.findUnique({ where: { key: 'projects_seeded_en_v1' } });
  if (!seededFlagEn) {
    for (const [sortOrder, project] of projects.entries()) {
      const saved = await prisma.project.upsert({ where: { slug: project.slug }, update: project, create: { ...project, publishedAt: project.status === 'published' ? new Date() : undefined, sortOrder } });
      const tech = await prisma.technology.findMany({ where: { slug: { in: ['next-js', 'react', 'typescript', 'node-js', 'postgresql', 'prisma'] } } });
      await prisma.projectTechnology.deleteMany({ where: { projectId: saved.id } });
      await prisma.projectTechnology.createMany({ data: tech.map((technology, index) => ({ projectId: saved.id, technologyId: technology.id, sortOrder: index })), skipDuplicates: true });
      const category = await prisma.category.findFirst({ where: { slug: project.projectType?.toLowerCase().replace(/[^a-z0-9]+/g, '-') } });
      await prisma.projectCategory.deleteMany({ where: { projectId: saved.id } });
      if (category) await prisma.projectCategory.create({ data: { projectId: saved.id, categoryId: category.id } });
      if (liveUrls[project.slug]) await prisma.projectLink.upsert({ where: { id: `seed-live-${project.slug}` }, update: { url: liveUrls[project.slug] }, create: { id: `seed-live-${project.slug}`, projectId: saved.id, label: 'Live demo', url: liveUrls[project.slug], type: 'live', isPublic: true } });
    }
    await prisma.setting.create({ data: { key: 'projects_seeded_en_v1', value: true } });
  }
  const settings = { contact_email: 'hello@halonso.digital', linkedin_url: 'https://www.linkedin.com/', github_url: 'https://github.com/BetazoDev', upwork_url: 'https://www.upwork.com/', resume_url: '/Humberto Alonso Lopez CV 2026.pdf' };
  for (const [key, value] of Object.entries(settings)) await prisma.setting.upsert({ where: { key }, update: {}, create: { key, value } });
}
main().finally(() => prisma.$disconnect());
