import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();
const technologies = ['Next.js', 'React', 'TypeScript', 'Node.js', 'Express', 'PostgreSQL', 'Prisma', 'Supabase', 'n8n', 'WordPress'];
const categories = ['AI Automation', 'Headless CMS', 'WordPress', 'SaaS', 'Business Platform', 'Lead Generation'];
const projects = [
  { title: 'Retrato', slug: 'retrato', subtitle: 'A headless editorial platform for independent publishing.', shortSummary: 'A premium editorial workflow connecting content, media and public storytelling.', projectType: 'Headless CMS', role: 'Architecture, frontend & CMS', year: 2026, status: 'published' as const, featured: true, problem: 'A modern publication needed a flexible editorial system without sacrificing visual direction.', solution: 'A headless content architecture with a custom frontend and reusable story presentation patterns.', result: 'A faster publishing workflow and a more distinctive reading experience.' },
  { title: 'Lumina Dental Studio', slug: 'lumina-dental-studio', subtitle: 'A conversion-focused digital experience for a modern clinic.', shortSummary: 'A calm, high-trust digital presence designed around patient action.', projectType: 'Business platform', role: 'Product design & development', year: 2026, status: 'published' as const, featured: true, problem: 'The clinic needed to communicate expertise and make the next step feel effortless.', solution: 'A responsive experience that combines clear service architecture, trust signals and focused conversion paths.', result: 'A more coherent brand system and a simpler path from discovery to contact.' },
  { title: 'NeoProspector', slug: 'neo-prospector', subtitle: 'Lead intelligence from map data and automated workflows.', shortSummary: 'A prospecting dashboard that turns raw location data into useful sales lists.', projectType: 'AI & automation', role: 'Full-stack development', year: 2026, status: 'published' as const, featured: true, problem: 'Sales teams needed to move from scattered search results to structured, actionable prospecting.', solution: 'A dashboard with scraping orchestration, filters, exports and a clear operational workflow.', result: 'A reusable foundation for repeatable lead generation and qualification.' },
  { title: 'HidroDemo', slug: 'hidrodemo', subtitle: 'A B2B analytics platform for media intelligence.', shortSummary: 'A data-heavy business platform made easier to understand and operate.', projectType: 'Business platform', role: 'Frontend, backend & deployment', year: 2026, status: 'published' as const, featured: false, problem: 'Complex media data needed to become a daily decision-making tool for teams.', solution: 'A structured dashboard experience backed by a dedicated API and persistent data layer.', result: 'A clearer operational view of the information that drives commercial decisions.' },
  { title: 'Diabolical Services', slug: 'diabolical-services', subtitle: 'A technical portfolio and systems studio.', shortSummary: 'A digital home for a studio building products, automations and internal tools.', projectType: 'Studio platform', role: 'Design system & development', year: 2026, status: 'published' as const, featured: false, problem: 'A broad range of technical capabilities needed a sharper commercial narrative.', solution: 'A modular site system that presents projects as business outcomes and technical case studies.', result: 'A stronger sales surface for high-value digital work.' },
  { title: 'Powersthenics', slug: 'powersthenics', subtitle: 'Plataforma Powersthenics.', shortSummary: 'Plataforma web orientada a entrenamiento y rendimiento.', projectType: 'Web Development', role: 'Diseño y desarrollo', year: 2026, status: 'published' as const, featured: true, problem: 'Presentar el producto y su propuesta con claridad.', solution: 'Una experiencia web responsive basada en la identidad del producto.', result: 'Una demostración pública lista para validación comercial.' },
  { title: 'X3 Padel Club', slug: 'x3-padel-club', subtitle: 'Sitio web para el club de pádel X3.', shortSummary: 'Presencia digital y experiencia de marca para X3 Padel Club.', projectType: 'Business website', role: 'UI/UX y desarrollo', year: 2026, status: 'published' as const, featured: true, problem: 'El club necesitaba una presencia digital reconocible.', solution: 'Un sitio responsive alineado con su identidad visual.', result: 'Una plataforma pública clara para presentar el club.' },
  { title: 'Monkey Trip', slug: 'monkey-trip', subtitle: 'Landing page en HTML para Monkey Trip.', shortSummary: 'Landing page ligera para comunicar una experiencia de viaje.', projectType: 'Landing page', role: 'Frontend', year: 2026, status: 'published' as const, featured: false, problem: 'Comunicar una oferta de forma directa.', solution: 'Una landing simple, rápida y enfocada.', result: 'Una página pública de carga inmediata.' },
  { title: 'Diabolical Landing Page', slug: 'diabolical-landing-page', subtitle: 'Página corporativa de alto rendimiento.', shortSummary: 'Página enfocada en UI/UX moderna y Core Web Vitals optimizados.', projectType: 'Corporate site', role: 'Frontend y performance', year: 2026, status: 'published' as const, featured: true, problem: 'La agencia necesitaba una narrativa comercial y técnica sólida.', solution: 'Una landing modular con identidad visual y rendimiento optimizado.', result: 'Mejor presentación de servicios y capacidades.' },
  { title: 'Mynd', slug: 'mynd', subtitle: 'Plataforma web para Mynd.', shortSummary: 'Experiencia web responsive para la plataforma Mynd.', projectType: 'Web platform', role: 'Frontend', year: 2026, status: 'published' as const, featured: false, problem: 'Presentar la plataforma en una interfaz coherente.', solution: 'Desarrollo frontend responsive y reusable.', result: 'Una presencia web lista para producción.' },
  { title: 'Diabolical Media Manager', slug: 'diabolical-media-manager', subtitle: 'Sistema interno de gestión de imágenes y CDN.', shortSummary: 'Optimización automática WebP/AVIF y servicio dinámico de CDN.', projectType: 'Internal tool', role: 'Full-stack', year: 2026, status: 'published' as const, featured: true, problem: 'Los assets necesitaban un flujo centralizado y optimizado.', solution: 'Gestor de medios con procesamiento automático y distribución CDN.', result: 'Menor peso de imágenes y administración centralizada.' },
  { title: 'Project Manager System', slug: 'project-manager-system', subtitle: 'Sistema interno de gestión de proyectos.', shortSummary: 'Pipeline Kanban para optimizar equipos de producción web.', projectType: 'Internal tool', role: 'Full-stack', year: 2024, status: 'published' as const, featured: false, problem: 'El equipo necesitaba visibilidad del flujo de producción.', solution: 'Un sistema Kanban con estados, responsables y seguimiento.', result: 'Operación más ordenada y trazable.' },
  { title: 'NailFlow', slug: 'nailflow', subtitle: 'Automatización de reservas para técnicas de uñas.', shortSummary: 'Plataforma personalizada para profesionales de belleza en LATAM.', projectType: 'SaaS', role: 'Product design y frontend', year: 2025, status: 'published' as const, featured: true, problem: 'Las reservas manuales consumían tiempo y generaban errores.', solution: 'Una experiencia de reservas automatizada y adaptada al mercado.', result: 'Menos trabajo operativo y mejor experiencia para clientes.' },
  { title: 'ERP Diabolical', slug: 'erp-diabolical', subtitle: 'Sistema de planificación de recursos empresariales.', shortSummary: 'Gestión interna y operaciones para Diabolical Projects.', projectType: 'ERP', role: 'Arquitectura y desarrollo', year: 2024, status: 'published' as const, featured: true, problem: 'La operación interna estaba distribuida entre herramientas.', solution: 'Un sistema central para procesos, recursos y seguimiento.', result: 'Mayor control operativo desde una sola plataforma.' },
  { title: 'TopLendr', slug: 'toplendr', subtitle: 'Plataforma de préstamos inmobiliarios.', shortSummary: 'Soluciones de alta velocidad para fix & flip, alquiler y construcción.', projectType: 'Fintech', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'Los inversionistas necesitaban entender y solicitar financiamiento con rapidez.', solution: 'Una experiencia de contenido y conversión enfocada en productos financieros.', result: 'Un recorrido más directo desde la necesidad hasta la solicitud.' },
  { title: 'Real Authority Media', slug: 'real-authority-media', subtitle: 'Agencia de medios y autoridad digital.', shortSummary: 'Presencia digital para marcas y personalidades de alto impacto.', projectType: 'Agency website', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'La agencia necesitaba comunicar autoridad y resultados.', solution: 'Una estructura editorial orientada a posicionamiento y servicios.', result: 'Una presencia coherente con clientes de alto perfil.' },
  { title: 'Alan Stalcup Scholarship', slug: 'alan-stalcup-scholarship', subtitle: 'Programa de becas en Austin, Texas.', shortSummary: 'Sitio dedicado a apoyar el camino educativo de estudiantes.', projectType: 'Education', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'El programa necesitaba explicar su misión y proceso.', solution: 'Un sitio accesible con información clara para aspirantes.', result: 'Mayor claridad para estudiantes y comunidades.' },
  { title: 'Arouna Toure', slug: 'arouna-toure', subtitle: 'Blog personal y plataforma de marca.', shortSummary: 'Ideas, experiencias y perspectivas profesionales.', projectType: 'Blog', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'La marca personal necesitaba un espacio editorial propio.', solution: 'Una plataforma flexible para publicación y posicionamiento.', result: 'Un canal directo para desarrollar audiencia y autoridad.' },
  { title: 'Lipschitz Strategies', slug: 'lipschitz-strategies', subtitle: 'Consultoría estratégica para startups.', shortSummary: 'Marketing, crecimiento empresarial y estrategia técnica.', projectType: 'Consulting', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'La consultoría necesitaba estructurar una oferta compleja.', solution: 'Un sitio orientado a explicar servicios y generar contacto.', result: 'Una narrativa comercial más clara.' },
  { title: 'Prasenjit Bhaumik', slug: 'prasenjit-bhaumik', subtitle: 'Portafolio profesional de desarrollo de software.', shortSummary: 'Aplicaciones web modernas, experiencia y proyectos.', projectType: 'Portfolio', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'El profesional necesitaba presentar experiencia y capacidades.', solution: 'Un portafolio organizado alrededor de trabajo y perfil.', result: 'Una presencia profesional fácil de compartir.' },
  { title: 'Noam Lamdan', slug: 'noam-lamdan', subtitle: 'Diseño y pensamiento arquitectónico desde Toronto.', shortSummary: 'Exploración de la intersección entre arquitectura y vida moderna.', projectType: 'Architecture', role: 'WordPress development', year: 2024, status: 'published' as const, featured: false, problem: 'El trabajo arquitectónico requería una presentación editorial.', solution: 'Una plataforma visual para ideas, proyectos y práctica.', result: 'Una experiencia digital acorde con el enfoque del autor.' },
];
const liveUrls: Record<string, string> = {
  retrato: 'https://retrato.halonso.digital/', powersthenics: 'https://powers-demo.diabolicalservices.tech/', 'x3-padel-club': 'https://x3padelclub.diabolicalservices.tech/', 'monkey-trip': 'https://monkey-trip.diabolicalservices.tech/', 'diabolical-landing-page': 'https://diabolicalservices.tech/', mynd: 'https://mynd.diabolicalservices.tech/', nailflow: 'https://demo.diabolicalservices.tech/', toplendr: 'https://toplendr.com/', 'real-authority-media': 'https://realauthoritymedia.com/', 'alan-stalcup-scholarship': 'https://alanstalcupscholarship.com/', 'arouna-toure': 'https://arounatoure.blog/', 'lipschitz-strategies': 'https://lipschitzstrategies.com/', 'prasenjit-bhaumik': 'https://prasenjitbhaumikplano.com/', 'noam-lamdan': 'https://toronto.noamlamdan.net/'
};

async function main() {
  const email = process.env.ADMIN_EMAIL ?? 'admin@halonso.digital';
  const password = process.env.ADMIN_PASSWORD;
  if (!password) throw new Error('ADMIN_PASSWORD is required for the initial seed');
  await prisma.user.upsert({ where: { email }, update: {}, create: { name: 'Humberto Alonso', email, passwordHash: await bcrypt.hash(password, 12), role: 'admin' } });
  const credentialFlag = await prisma.setting.findUnique({ where: { key: 'admin_credential_initialized' } });
  if (!credentialFlag) {
    await prisma.$transaction([
      prisma.user.update({ where: { email }, data: { passwordHash: '$2b$12$Pu1N5y9gpjq0F1JwB4qbauUzMDTvAD241pegYVBspM73fH1.mJdFO' } }),
      prisma.setting.create({ data: { key: 'admin_credential_initialized', value: true } }),
    ]);
  }
  for (const name of technologies) await prisma.technology.upsert({ where: { slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-') }, update: {}, create: { name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-') } });
  for (const name of categories) await prisma.category.upsert({ where: { slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-') }, update: {}, create: { name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-') } });
  for (const [sortOrder, project] of projects.entries()) {
    const saved = await prisma.project.upsert({ where: { slug: project.slug }, update: project, create: { ...project, publishedAt: project.status === 'published' ? new Date() : undefined, sortOrder } });
    const tech = await prisma.technology.findMany({ where: { slug: { in: ['next-js', 'react', 'typescript', 'node-js', 'postgresql', 'prisma'] } } });
    await prisma.projectTechnology.deleteMany({ where: { projectId: saved.id } });
    await prisma.projectTechnology.createMany({ data: tech.map((technology, index) => ({ projectId: saved.id, technologyId: technology.id, sortOrder: index })), skipDuplicates: true });
    const category = await prisma.category.findFirst({ where: { slug: project.projectType?.toLowerCase().replace(/[^a-z0-9]+/g, '-') } });
    await prisma.projectCategory.deleteMany({ where: { projectId: saved.id } });
    if (category) await prisma.projectCategory.create({ data: { projectId: saved.id, categoryId: category.id } });
    if (liveUrls[project.slug]) await prisma.projectLink.upsert({ where: { id: `seed-live-${project.slug}` }, update: { url: liveUrls[project.slug] }, create: { id: `seed-live-${project.slug}`, projectId: saved.id, label: 'Live demo', url: liveUrls[project.slug], type: 'live', isPublic: true } });
  }
  const settings = { contact_email: 'hello@halonso.digital', linkedin_url: 'https://www.linkedin.com/', github_url: 'https://github.com/BetazoDev', upwork_url: 'https://www.upwork.com/', resume_url: '/Humberto Alonso Lopez CV 2026.pdf' };
  for (const [key, value] of Object.entries(settings)) await prisma.setting.upsert({ where: { key }, update: {}, create: { key, value } });
}
main().finally(() => prisma.$disconnect());
