'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { adminFetch, clearToken } from '@/lib/admin-api';
const keys = [['contact_email', 'Correo'], ['linkedin_url', 'LinkedIn'], ['github_url', 'GitHub'], ['upwork_url', 'Upwork'], ['resume_url', 'CV']];
export default function SettingsPage() {
  const router = useRouter(); const [values, setValues] = useState<Record<string, string>>({}); const [message, setMessage] = useState(''); const [passwordMessage, setPasswordMessage] = useState('');
  useEffect(() => { adminFetch('/api/admin/settings').then(async (response) => { if (response.ok) setValues(Object.fromEntries((await response.json()).map((item: { key: string; value: unknown }) => [item.key, String(item.value ?? '')]))); }); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setMessage('Guardando…'); await Promise.all(Object.entries(values).map(([key, value]) => adminFetch(`/api/admin/settings/${key}`, { method: 'PUT', body: JSON.stringify({ value }) }))); setMessage('Ajustes guardados.'); }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (form.get('newPassword') !== form.get('confirmation')) return setPasswordMessage('La confirmación no coincide.'); const response = await adminFetch('/api/auth/password', { method: 'PUT', body: JSON.stringify({ currentPassword: form.get('currentPassword'), newPassword: form.get('newPassword') }) }); if (!response.ok) return setPasswordMessage('No se pudo cambiar. Revisa la contraseña actual y usa al menos 12 caracteres.'); clearToken(); router.replace('/admin/login'); }
  return <><p className="font-mono text-[10px] uppercase tracking-[.3em] text-[#8b78ff]">Sitio</p><h1 className="my-8 text-6xl font-bold">Ajustes</h1><div className="grid max-w-5xl gap-8 lg:grid-cols-2"><form onSubmit={save} className="border border-white/15 p-6"><h2 className="mb-6 text-xl font-bold">Información pública</h2>{keys.map(([key, label]) => <label key={key} className="mb-6 block text-xs text-white/50">{label}<input value={values[key] ?? ''} onChange={(e) => setValues((current) => ({ ...current, [key]: e.target.value }))} className="mt-2 w-full border-b border-white/20 bg-transparent py-3 text-white outline-none" /></label>)}<button className="bg-[#7057ff] px-6 py-4 font-mono text-[10px] uppercase tracking-widest">Guardar</button>{message && <span className="ml-5 text-xs text-[#8b78ff]">{message}</span>}</form><form onSubmit={changePassword} className="h-fit border border-white/15 p-6"><h2 className="mb-6 text-xl font-bold">Seguridad</h2><input name="currentPassword" type="password" required placeholder="Contraseña actual" className="mb-5 w-full border-b border-white/20 bg-transparent py-3 outline-none" /><input name="newPassword" type="password" required minLength={12} placeholder="Nueva contraseña" className="mb-5 w-full border-b border-white/20 bg-transparent py-3 outline-none" /><input name="confirmation" type="password" required minLength={12} placeholder="Confirmar contraseña" className="mb-6 w-full border-b border-white/20 bg-transparent py-3 outline-none" /><button className="border border-[#7057ff] px-6 py-4 font-mono text-[10px] uppercase tracking-widest text-[#8b78ff]">Cambiar contraseña</button>{passwordMessage && <p className="mt-4 text-xs text-red-400">{passwordMessage}</p>}</form></div></>;
}
