'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, Eye, EyeOff, Search, Trash2 } from 'lucide-react';
import { adminFetch } from '@/lib/admin-api';
type Item = { id: string; title: string; slug: string; status: string; showOnHomepage: boolean; updatedAt: string; shortSummary?: string };
export default function AdminProjectsPage() {
  const [items, setItems] = useState<Item[]>([]); const [query, setQuery] = useState('');
  const load = () => adminFetch('/api/admin/projects').then(async (response) => { if (response.ok) setItems(await response.json()); });
  useEffect(() => { void load(); }, []);
  async function remove(id: string) { if (!confirm('¿Eliminar este proyecto de forma permanente?')) return; await adminFetch(`/api/admin/projects/${id}`, { method: 'DELETE' }); void load(); }
  async function toggleHomepage(item: Item) { const response = await adminFetch(`/api/admin/projects/${item.id}`, { method: 'PATCH', body: JSON.stringify({ showOnHomepage: !item.showOnHomepage }) }); if (response.ok) setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, showOnHomepage: !item.showOnHomepage } : entry)); }
  const shown = items.filter((item) => item.title.toLowerCase().includes(query.toLowerCase()));
  return <>
    <header className="flex flex-wrap items-end justify-between gap-6 border-b border-white/10 pb-10"><div><p className="font-mono text-[10px] uppercase tracking-[.3em] text-[#8b78ff]">Content library</p><h1 className="mt-5 text-5xl font-bold md:text-7xl">Proyectos</h1><p className="mt-4 text-sm text-white/45">Gestiona el contenido con la misma jerarquía visual del portafolio.</p></div><Link href="/admin/projects/new" className="border border-[#8b78ff] bg-[#8b78ff]/10 px-6 py-4 font-mono text-[10px] uppercase tracking-widest text-[#b6a8ff]">Nuevo proyecto +</Link></header>
    <label className="my-10 flex items-center gap-4 border-b border-white/15 py-4 focus-within:border-[#8b78ff]"><Search size={16} className="text-white/35"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nombre…" className="w-full bg-transparent text-sm outline-none"/></label>
    <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{shown.map((item, index) => <article key={item.id} className="group relative min-h-72 overflow-hidden border border-white/10 bg-[#101011] p-6 transition hover:border-[#8b78ff]/70"><div className="absolute inset-0 opacity-30 [background:radial-gradient(circle_at_80%_20%,rgba(112,87,255,.35),transparent_38%)]"/><div className="relative flex h-full min-h-60 flex-col"><div className="flex justify-between font-mono text-[9px] uppercase tracking-widest text-white/35"><span>{String(index + 1).padStart(2, '0')}</span><span className={item.status === 'published' ? 'text-emerald-400' : 'text-amber-300'}>{item.status}</span></div><div className="mt-auto"><p className="font-mono text-[9px] text-[#8b78ff]">/{item.slug}</p><h2 className="mt-3 text-3xl font-bold leading-tight">{item.title}</h2><p className="mt-3 line-clamp-2 text-xs leading-5 text-white/45">{item.shortSummary || 'Sin resumen editorial.'}</p></div><div className="mt-6 flex items-center justify-between border-t border-white/10 pt-5"><Link href={`/admin/projects/${item.id}`} className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-[#b6a8ff]">Editar <ArrowUpRight size={13}/></Link><div className="flex items-center gap-4"><button type="button" onClick={() => toggleHomepage(item)} aria-label={item.showOnHomepage ? `Ocultar ${item.title} del portafolio` : `Mostrar ${item.title} en el portafolio`} title={item.showOnHomepage ? 'Visible en el portafolio' : 'Oculto del portafolio'} className={item.showOnHomepage ? 'text-[#b6a8ff] hover:text-white' : 'text-white/30 hover:text-white'}>{item.showOnHomepage ? <Eye size={16}/> : <EyeOff size={16}/>}</button><button onClick={() => remove(item.id)} aria-label={`Eliminar ${item.title}`} className="text-white/30 hover:text-red-400"><Trash2 size={15}/></button></div></div></div></article>)}</div>
    {!shown.length && <p className="border border-white/10 p-12 text-center font-mono text-[10px] uppercase tracking-widest text-white/35">No hay proyectos que coincidan.</p>}
  </>;
}
