'use client';
import { FormEvent, useEffect, useState } from 'react';
import { adminFetch } from '@/lib/admin-api';
type Media = { id: string; originalFilename: string; publicUrl: string | null }; type Relation = { id: string; type: string; media: Media }; type LinkItem = { id: string; label: string; url: string; type: string }; type Section = { id: string; type: string; title: string | null; content: unknown; sortOrder: number };
export function ProjectRelations({ projectId }: { projectId: string }) {
  const [library, setLibrary] = useState<Media[]>([]); const [relations, setRelations] = useState<Relation[]>([]); const [links, setLinks] = useState<LinkItem[]>([]); const [sections, setSections] = useState<Section[]>([]); const [message, setMessage] = useState('');
  const load = async () => { const [mediaResponse, projectResponse] = await Promise.all([adminFetch('/api/admin/media'), adminFetch(`/api/admin/projects/${projectId}`)]); if (mediaResponse.ok) setLibrary(await mediaResponse.json()); if (projectResponse.ok) { const project = await projectResponse.json(); setRelations(project.media ?? []); setLinks(project.links ?? []); setSections(project.sections ?? []); } };
  useEffect(() => { void load(); }, [projectId]);
  async function attachMedia(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await adminFetch(`/api/admin/projects/${projectId}/media`, { method: 'POST', body: JSON.stringify({ mediaId: form.get('mediaId'), type: form.get('type'), sortOrder: relations.length }) }); setMessage(response.ok ? 'Medio asociado.' : 'No se pudo asociar.'); if (response.ok) void load(); }
  async function addLink(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await adminFetch(`/api/admin/projects/${projectId}/links`, { method: 'POST', body: JSON.stringify({ label: form.get('label'), url: form.get('url'), type: form.get('type'), isPublic: true, sortOrder: links.length }) }); setMessage(response.ok ? 'Enlace agregado.' : 'No se pudo agregar.'); if (response.ok) { event.currentTarget.reset(); void load(); } }
  async function addSection(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); let content: unknown; try { content = JSON.parse(String(form.get('content'))); } catch { content = { text: String(form.get('content')) }; } const response = await adminFetch(`/api/admin/projects/${projectId}/sections`, { method: 'POST', body: JSON.stringify({ title: form.get('title') || undefined, type: form.get('type'), content, sortOrder: sections.length }) }); setMessage(response.ok ? 'Sección agregada.' : 'No se pudo agregar.'); if (response.ok) { event.currentTarget.reset(); void load(); } }
  async function remove(path: string) { if (!confirm('¿Eliminar este elemento?')) return; await adminFetch(path, { method: 'DELETE' }); void load(); }
  return <div className="mt-12 grid gap-8 xl:grid-cols-3"><Panel title="Medios"><form onSubmit={attachMedia} className="grid gap-3"><select required name="mediaId" className="bg-[#0c0c0d] p-3 text-sm"><option value="">Seleccionar archivo</option>{library.map((media) => <option key={media.id} value={media.id}>{media.originalFilename}</option>)}</select><select name="type" className="bg-[#0c0c0d] p-3 text-sm"><option value="thumbnail">Thumbnail</option><option value="cover">Cover</option><option value="gallery">Galería</option><option value="architecture">Arquitectura</option><option value="workflow">Workflow</option></select><button className="border border-[#7057ff] p-3 text-xs">Asociar +</button></form><List>{relations.map((item) => <Row key={item.id} label={`${item.type}: ${item.media.originalFilename}`} remove={() => remove(`/api/admin/projects/${projectId}/media/${item.id}`)} />)}</List></Panel><Panel title="Enlaces"><form onSubmit={addLink} className="grid gap-3"><input required name="label" placeholder="Etiqueta" className="bg-transparent p-3 ring-1 ring-white/15" /><input required name="url" type="url" placeholder="https://" className="bg-transparent p-3 ring-1 ring-white/15" /><select name="type" className="bg-[#0c0c0d] p-3"><option value="live">Live</option><option value="github">GitHub</option><option value="video">Video</option><option value="docs">Docs</option><option value="upwork">Upwork</option><option value="other">Otro</option></select><button className="border border-[#7057ff] p-3 text-xs">Agregar +</button></form><List>{links.map((item) => <Row key={item.id} label={`${item.label}: ${item.url}`} remove={() => remove(`/api/admin/links/${item.id}`)} />)}</List></Panel><Panel title="Caso de estudio"><form onSubmit={addSection} className="grid gap-3"><input name="title" placeholder="Título" className="bg-transparent p-3 ring-1 ring-white/15" /><select name="type" className="bg-[#0c0c0d] p-3"><option value="text">Texto</option><option value="image">Imagen</option><option value="gallery">Galería</option><option value="metrics">Métricas</option><option value="quote">Cita</option><option value="architecture">Arquitectura</option><option value="workflow">Workflow</option><option value="video">Video</option></select><textarea required name="content" rows={5} placeholder={'Texto o JSON: {"text":"Contenido"}'} className="bg-transparent p-3 ring-1 ring-white/15" /><button className="border border-[#7057ff] p-3 text-xs">Agregar +</button></form><List>{sections.map((item) => <Row key={item.id} label={`${item.sortOrder + 1}. ${item.title ?? item.type}`} remove={() => remove(`/api/admin/sections/${item.id}`)} />)}</List></Panel>{message && <p className="font-mono text-xs text-[#8b78ff] xl:col-span-3">{message}</p>}</div>;
}
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border border-white/15 p-5"><h2 className="mb-6 font-mono text-[10px] uppercase tracking-widest text-[#8b78ff]">{title}</h2>{children}</section>; } function List({ children }: { children: React.ReactNode }) { return <div className="mt-6 border-t border-white/15">{children}</div>; } function Row({ label, remove }: { label: string; remove: () => void }) { return <div className="flex items-center justify-between gap-3 border-b border-white/10 py-3 text-xs"><span className="truncate">{label}</span><button type="button" onClick={remove} className="font-mono text-[9px] uppercase text-red-400">Quitar</button></div>; }
