'use client';
import { FormEvent, useEffect, useState } from 'react';
import { adminFetch } from '@/lib/admin-api';
type Media = { id: string; originalFilename: string; publicUrl: string | null }; type Relation = { id: string; type: string; media: Media }; type LinkItem = { id: string; label: string; url: string; type: string }; type Section = { id: string; type: string; title: string | null; content: unknown; sortOrder: number };
export function ProjectRelations({ projectId }: { projectId: string }) {
  const [library, setLibrary] = useState<Media[]>([]); const [relations, setRelations] = useState<Relation[]>([]); const [links, setLinks] = useState<LinkItem[]>([]); const [sections, setSections] = useState<Section[]>([]); const [message, setMessage] = useState('');
  const load = async () => { const [mediaResponse, projectResponse] = await Promise.all([adminFetch('/api/admin/media'), adminFetch(`/api/admin/projects/${projectId}`)]); if (mediaResponse.ok) setLibrary(await mediaResponse.json()); if (projectResponse.ok) { const project = await projectResponse.json(); setRelations(project.media ?? []); setLinks(project.links ?? []); setSections(project.sections ?? []); } };
  useEffect(() => { void load(); }, [projectId]);
  async function attachMedia(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await adminFetch(`/api/admin/projects/${projectId}/media`, { method: 'POST', body: JSON.stringify({ mediaId: form.get('mediaId'), type: form.get('type'), sortOrder: relations.length }) }); setMessage(response.ok ? 'Medio asociado.' : 'No se pudo asociar.'); if (response.ok) void load(); }
  async function addLink(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await adminFetch(`/api/admin/projects/${projectId}/links`, { method: 'POST', body: JSON.stringify({ label: form.get('label'), url: form.get('url'), type: form.get('type'), isPublic: true, sortOrder: links.length }) }); setMessage(response.ok ? 'Enlace agregado.' : 'No se pudo agregar.'); if (response.ok) { event.currentTarget.reset(); void load(); } }
  async function addSection(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); let content: unknown; try { content = JSON.parse(String(form.get('content'))); } catch { content = { text: String(form.get('content')) }; } const response = await adminFetch(`/api/admin/projects/${projectId}/sections`, { method: 'POST', body: JSON.stringify({ title: form.get('title') || undefined, type: form.get('type'), content, sortOrder: sections.length }) }); setMessage(response.ok ? 'Sección agregada.' : 'No se pudo agregar.'); if (response.ok) { event.currentTarget.reset(); void load(); } }
  async function remove(path: string) { if (!confirm('¿Eliminar este elemento?')) return; await adminFetch(path, { method: 'DELETE' }); void load(); }
  return <div className="grid gap-6 xl:grid-cols-3"><Panel title="Medios" description="Cover, miniatura, arquitectura y galería."><form onSubmit={attachMedia} className="grid gap-5"><Select name="mediaId" required><option value="">Seleccionar archivo</option>{library.map((media) => <option key={media.id} value={media.id}>{media.originalFilename}</option>)}</Select><Select name="type"><option value="thumbnail">Thumbnail</option><option value="cover">Cover</option><option value="gallery">Galería</option><option value="architecture">Arquitectura</option><option value="workflow">Workflow</option></Select><Action>Asociar medio +</Action></form><List>{relations.map((item) => <Row key={item.id} label={`${item.type}: ${item.media.originalFilename}`} remove={() => remove(`/api/admin/projects/${projectId}/media/${item.id}`)} />)}</List></Panel><Panel title="Enlaces" description="Demo, código, documentación y video."><form onSubmit={addLink} className="grid gap-5"><Input name="label" required placeholder="Etiqueta"/><Input name="url" required type="url" placeholder="https://"/><Select name="type"><option value="live">Live</option><option value="github">GitHub</option><option value="video">Video</option><option value="docs">Docs</option><option value="upwork">Upwork</option><option value="other">Otro</option></Select><Action>Agregar enlace +</Action></form><List>{links.map((item) => <Row key={item.id} label={`${item.label}: ${item.url}`} remove={() => remove(`/api/admin/links/${item.id}`)} />)}</List></Panel><Panel title="Secciones" description="Bloques adicionales para el caso de proyecto."><form onSubmit={addSection} className="grid gap-5"><Input name="title" placeholder="Título"/><Select name="type"><option value="text">Texto</option><option value="image">Imagen</option><option value="gallery">Galería</option><option value="metrics">Métricas</option><option value="quote">Cita</option><option value="architecture">Arquitectura</option><option value="workflow">Workflow</option><option value="video">Video</option></Select><textarea required name="content" rows={4} placeholder={'Texto o JSON: {"text":"Contenido"}'} className="border border-white/10 bg-transparent p-4 text-sm outline-none focus:border-[#a855f7]"/><Action>Agregar sección +</Action></form><List>{sections.map((item) => <Row key={item.id} label={`${item.sortOrder + 1}. ${item.title ?? item.type}`} remove={() => remove(`/api/admin/sections/${item.id}`)} />)}</List></Panel>{message && <p className="font-mono text-xs text-[#a855f7] xl:col-span-3">{message}</p>}</div>;
}
function Panel({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="border border-white/10 bg-[#101011] p-6"><h2 className="font-mono text-[10px] uppercase tracking-widest text-[#a855f7]">{title}</h2><p className="mb-7 mt-3 text-xs leading-5 text-white/40">{description}</p>{children}</section>; }
function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className="border-x-0 border-b border-t-0 border-white/15 bg-transparent px-0 py-4 text-sm outline-none focus:border-[#a855f7]"/>; }
function Select(props: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className="border-x-0 border-b border-t-0 border-white/15 bg-transparent px-0 py-4 text-sm outline-none focus:border-[#a855f7]"/>; }
function Action({ children }: { children: React.ReactNode }) { return <button className="border border-[#a855f7] bg-[#a855f7]/10 p-4 font-mono text-[10px] uppercase tracking-widest text-[#c084fc] hover:bg-[#9333ea] hover:text-white transition-colors">{children}</button>; }
function List({ children }: { children: React.ReactNode }) { return <div className="mt-7 border-t border-white/10">{children}</div>; }
function Row({ label, remove }: { label: string; remove: () => void }) { return <div className="flex items-center justify-between gap-3 border-b border-white/10 py-4 text-xs"><span className="truncate text-white/60">{label}</span><button type="button" onClick={remove} className="font-mono text-[9px] uppercase text-red-400">Quitar</button></div>; }
